name: 'SWM GitHub Actions Basic' # 없어도됨, 하지만 없으면 찾기 힘듦, 외부에서 이 github action API 호출할 때도 사용

on: push # 필수 # trigger : push 했을 때 실행시켜라
#on : ['push', 'pull_request'] # 배열로 만들면 trigger 추가 실행 가능

jobs: # 필수 # 이 workflow로 하겠다
  first-job: # second-job 등 원하는 만큼 추가 가능 # job마다 격리된 빌드 서버가 돌아감 # 각 서버끼리 전달이 안 됨
    name: 'First Job' # job 마다 이름

    runs-on: ubuntu-latest # windows or ubuntu or mac

    steps: # 배열 요소 하나하나가 task=action # 하다 실패하면 뒤에꺼는 실행 안 됨(default)(실패해도 계속 실행하게 할 수도 있음)
    - name: Say Hello World 1 
      shell: bash # shell은 편한거 써도 됨
      run: |
        echo "Hello World from step 1"

    - name: Say Hello World 2
      shell: pwsh
      run: |
        echo "Hello World from step 2"